version: '2'
services:
  mosca:
    image: matteocollina/mosca
    ports:
      - "8080:80"
      - "1883"
    expose:
      - "1883"
      - "8080"
    networks:
      - mynet
    hostname: mosca

  random-sensors:
    build: .
    networks:
      - mynet
    depends_on:
      - mosca

networks:
  mynet:
    driver: bridge
